### ISSUE TITLE
Make cursor pointer in Details

### ISSUE THREAD

**Issue by romadryud** [artalar/mono#7]
Hi, I think it's better to have pointer cursor for details. I can prepare PR for it if needed :)

Before:
![image](https://user-images.githubusercontent.com/19193036/199118078-27b07d6e-d71b-441c-ae3e-826851844d08.png)

After: 
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/19193036/199118258-15cc3240-edaa-432d-9310-2e86c57b71c9.png">

**Comment by artalar** [comment]
Every default browser styles has a reason. Why do you think this is mistake?

**Comment by romadryud** [comment]
I'm not thinking this is mistake. Just because when I saw it first time I was thinking this is just text and `cursor: pointer` will be just one more indicator which tell user that he can click there and something will be appear.
